set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

if(WIN32)
    set(TOOL_EXECUTABLE_SUFFIX ".exe")
endif()

set(CH32_RISCV_TOOLCHAIN_TRIPLET "" CACHE STRING "RISC-V GCC target triplet. Empty means auto-detect.")
set(CH32_RISCV_TOOLCHAIN_CANDIDATES riscv-none-elf riscv-none-embed)

if(CH32_RISCV_TOOLCHAIN_TRIPLET)
    set(TARGET_TRIPLET "${CH32_RISCV_TOOLCHAIN_TRIPLET}")
else()
    foreach(candidate ${CH32_RISCV_TOOLCHAIN_CANDIDATES})
        string(REPLACE "-" "_" candidate_cache_name "CH32_${candidate}_GCC")
        find_program(${candidate_cache_name} "${candidate}-gcc${TOOL_EXECUTABLE_SUFFIX}")
        if(${candidate_cache_name})
            set(TARGET_TRIPLET "${candidate}")
            break()
        endif()
    endforeach()
endif()

if(NOT TARGET_TRIPLET)
    set(TARGET_TRIPLET "riscv-none-elf")
endif()

message(STATUS "CH32 RISC-V toolchain triplet: ${TARGET_TRIPLET}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_NINJA_FORCE_RESPONSE_FILE OFF CACHE BOOL "Do not force response files for every Ninja RISC-V command" FORCE)
set(CMAKE_ASM_COMPILER "${TARGET_TRIPLET}-gcc${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "asm compiler")
set(CMAKE_C_COMPILER "${TARGET_TRIPLET}-gcc${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "c compiler")
set(CMAKE_CXX_COMPILER "${TARGET_TRIPLET}-g++${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "c++ compiler")
set(CMAKE_OBJCOPY "${TARGET_TRIPLET}-objcopy${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "objcopy tool")
set(CMAKE_OBJDUMP "${TARGET_TRIPLET}-objdump${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "objdump tool")
set(CMAKE_SIZE "${TARGET_TRIPLET}-size${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "size tool")
set(CMAKE_DEBUGGER "${TARGET_TRIPLET}-gdb${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "debugger")
set(CMAKE_CPPFILT "${TARGET_TRIPLET}-c++filt${TOOL_EXECUTABLE_SUFFIX}" CACHE INTERNAL "c++filt")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "@")
set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS 1)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_LIBRARIES 1)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES 0)
set(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@")
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES 1)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0)
set(CMAKE_ASM_RESPONSE_FILE_LINK_FLAG "@")
set(CMAKE_ASM_USE_RESPONSE_FILE_FOR_OBJECTS 1)
set(CMAKE_ASM_USE_RESPONSE_FILE_FOR_LIBRARIES 1)
set(CMAKE_ASM_USE_RESPONSE_FILE_FOR_INCLUDES 0)

if(NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_CONFIGURATION_TYPES Debug Release RelWithDebInfo)
endif()
if(CMAKE_BUILD_TYPE STREQUAL "")
    set(CMAKE_BUILD_TYPE RelWithDebInfo)
endif()
set(CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE} CACHE STRING "Build Type" FORCE)
set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${CMAKE_CONFIGURATION_TYPES})

set(riscv_none_elf_debug "-Og -g")
set(riscv_none_elf_release "-DNDEBUG")
set(riscv_none_elf_relwithdebinfo "-ggdb3 ${riscv_none_elf_release}")

set(CMAKE_C_FLAGS_DEBUG ${riscv_none_elf_debug} CACHE INTERNAL "c compiler flags debug")
set(CMAKE_CXX_FLAGS_DEBUG ${riscv_none_elf_debug} CACHE INTERNAL "c++ compiler flags debug")
set(CMAKE_ASM_FLAGS_DEBUG ${riscv_none_elf_debug} CACHE INTERNAL "asm compiler flags debug")

set(CMAKE_C_FLAGS_RELEASE ${riscv_none_elf_release} CACHE INTERNAL "c compiler flags release")
set(CMAKE_CXX_FLAGS_RELEASE ${riscv_none_elf_release} CACHE INTERNAL "cxx compiler flags release")
set(CMAKE_ASM_FLAGS_RELEASE ${riscv_none_elf_release} CACHE INTERNAL "asm compiler flags release")

set(CMAKE_C_FLAGS_RELWITHDEBINFO ${riscv_none_elf_relwithdebinfo} CACHE INTERNAL "c compiler flags release")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO ${riscv_none_elf_relwithdebinfo} CACHE INTERNAL "cxx compiler flags release")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO ${riscv_none_elf_relwithdebinfo} CACHE INTERNAL "asm compiler flags release")
